Выполнил ДЗ pick
js-tasks-ru/js-20220311_lapshov30 pull request #3
Opened 2022-03-18 13:48 UTC by yodavan

2022-03-18 14:16 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-03-18 16:39 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
>  export const pick = (obj, ...fields) => {
проверьте в решении использование `let/const`

2022-03-18 16:42 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let item in newObj) {
В решении есть 
* 1 `Object.entries`
* 2 `map`
* 1 `fromEntries`
* 1 `some`
* 1 `for..in`
Как минимум половина данных операций в решении не требуется, не с точки зрения логики работы, ни с точки зрения производительности.
Внимательно посмотрите разбор задачи на занятии

2022-03-18 21:43 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-03-20 23:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-21 14:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-22 15:13 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathToObj = path.split('.');
👍 good 
лайк за использование замыкания

2022-03-22 15:14 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        const j = pathToObj.shift();
так делать нельзя, попробуйте вызвать `getter` повторно с другим объектом и Вы увидите что `pathToObj` имеет неверное значение

2022-03-22 15:15 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +          return undefined;
нельзя возвращать `undefined`

2022-03-22 15:15 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  const Arr = string.split('');
нельзя именовать переменные с заглавного символа.
C заглавного символа именуются только классы и функции-конструкторы

2022-03-22 15:16 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr));
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-03-22 15:16 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-03-25 12:52 UTC, dosandk approved these changes
👍 good

2022-03-25 13:27 UTC, merged